HOME_DIR = ..
sources_dir = .

project = hand-written-sample
exe_name = sample
cpp_sources =   main.cpp \
                fractions-pool-base.cpp \
                model-base.cpp \
                output.cpp \
                space.cpp \
                model.cpp \
                axis.cpp \
                fractions-pool.cpp \
                ${fraction_sources_list} \

include $$(HOME_DIR)/Makefile.inc
