HOME_DIR = ..
sources_dir = .

project = hand-written-sample
exe_name = sample
cpp_sources =   main.cpp \
                output.cpp \
                space.cpp \
                model.cpp \
                axis.cpp \
                fractions-pool.cpp \
                ${fraction_sources_list} \

LDFLAGS += -lpthread

include $$(HOME_DIR)/Makefile.inc
