HOME_DIR = ..
sources_dir = .

project = hand-written-sample
exe_name = sample
cpp_sources =   main.cpp \
                fractions-pool.cpp \
                fractions-pool-base.cpp \
                space.cpp \
                model.cpp \
                axis.cpp \
                fraction-1.cpp \
                output.cpp

include $(HOME_DIR)/Makefile.inc
