HOME_DIR = ..
sources_dir = .

project = hand-written-sample
exe_name = sample
cpp_sources =   main.cpp \
                fractions-pool.cpp \
                space.cpp \
                model.cpp \
                axis.cpp \
                config-reader.cpp

include $(HOME_DIR)/Makefile.inc
