#
# This is a config for modelling electron's distribution in
# 0-d laser-induced breakdown in O2 and N2 atmosphere
# with pressure 1 atm
# Note: particles count quantity synonim is 'particles_count'
model:
    name: Dry air in square 2d box
    cordinate_space_grid:
        x_coord:
            name: Coordinate X, cm
            division:
                mode: uniform
                min: -1
                max: 1
                segments_count: 1
    fractions:
        electrons:
            name: Electrons
            stabilisation: off
            extensive_quantities:
                particles_count:
                    name: Count of electrons
            
            fraction_space_grid:
                energy:
                    name: Electron's energy, eV
                    division:
                        mode: uniform
                        min: 1*1.602e-19
                        max: 30*1.602e-19
                        segments_count: 100
            
            intensive_quantities:
                velocity:
                    name: Velocity, cm/sec
                    counting: |
                        velocity = sqrt(2*energy / me);
                
                #nu_m_ee:
                #    name: Electron-electron transport collision frequency
                #    counting: |
                #        nu_m_ee = particles_count*velocity * 2.8e-15; // Fixme: need real electron transport cross-section
                
                nu_m_eo2:
                    name: Electron-O2 transport collision frequency
                    counting: |
                        nu_m_eo2 = 1.0 / (22e-3) * Na * velocity * 3.9e-15;
                
                big_a:
                    name: Coefficient 'A'
                    counting: |
                        big_a = 2*e_charge*e_charge*E_field*E_field /(3*me*nu_m_eo2);
                        
                
                energy_diffusion_coefficient:
                    name: Diffusion through energy axis coefficient
                    counting: |
                        energy_diffusion_coefficient = big_a*energy;
                
                big_u:
                    name: Flow through energy axis due to elastic e-e collision
                    counting: |
                        big_u = big_a / 2;
                
                elastic_col_eo2_flow:
                    name: Flow through energy axis due to elastic collision with air
                    counting: |
                        elastic_col_eo2_flow = -2*me/(Mair/Na) * nu_m_eo2*energy;
            
            init_quantities: |
                if (energy > 1*EV && energy < 2*EV)
                    particles_count = 1e16/20*1/100;
                
            sources: |
                // Here sources
                
            space_coords_derivatives: |
                x_coord.DER = 0;
            
            fraction_coords_derivatives: |
                energy.DER = big_u;
            
            boundary_conditions:
                x_coord:
                    top: wall
                    bottom: wall
            diffusion:
                x_coord: |
                    diffusion = 0;
                energy: |
                    diffusion = energy_diffusion_coefficient; // Test
        #################################################
        O2:
            name: Non-exited O2
            extensive_quantities:
                particles_count:
                    name: Count of air, moll
            
            intensive_quantities:
                pressure:
                    name: Air pressure
                    counting: |
                        // todo
            
            init_quantities: |
                particles_count = 0;
                
            sources: |
                // Here sources
                
            space_coords_derivatives: |
                x_coord.DER = 0;
            
            boundary_conditions:
                x_coord:
                    top: wall
                    bottom: wall
            diffusion:
                x_coord: |
                    diffusion = 0;
output:
    e_concentration_vs_energy:
        name: Electrons-concentration-vs-energy
        fraction: electrons
        quantity: particles_count
        space_point:
            x_coord: 0
        fraction_point:
            energy: 0
        output_axis:
            energy:
                points_count: 100
        points_count: 300
    
    big_u:
        name: big_u
        fraction: electrons
        quantity: big_u
        space_point:
            x_coord: 0
        fraction_point:
            energy: 0
        output_axis:
            energy:
                points_count: 100
        points_count: 300
    
    elastic_col_eo2_flow:
        name: elastic_col_eo2_flow
        fraction: electrons
        quantity: elastic_col_eo2_flow
        space_point:
            x_coord: 0
        fraction_point:
            energy: 0
        output_axis:
            energy:
                points_count: 100
        points_count: 300
    
    big_u:
        name: big_u
        fraction: electrons
        quantity: big_u
        space_point:
            x_coord: 0
        fraction_point:
            energy: 0
        output_axis:
            energy:
                points_count: 100
        points_count: 300
    
    nu_m_eo2:
        name: nu_m_eo2
        fraction: electrons
        quantity: nu_m_eo2
        space_point:
            x_coord: 0
        fraction_point:
            energy: 0
        output_axis:
            energy:
                points_count: 100
        points_count: 300
    
    energy_diff_coeff:
        name: energy_diff_coeff-vs-energy
        fraction: electrons
        quantity: energy_diffusion_coefficient
        space_point:
            x_coord: 0
        fraction_point:
            energy: 0
        output_axis:
            energy:
                points_count: 100
        points_count: 300
    
run_options:
    start_time: 0
    stop_time: 1e-5
    points_count: 100000
    #time_step: 5e-16
    threads_count: 5

constants:
    Mair: 0.029                 // kg / Moll        - Air molar mass
    Na: 6.02e23                 // particles / Moll - Avogadro number
    R: 8.3144                   // J / Moll*K       - Universal gase constant
    me: 9.10938291e-31          // kg               - Electron mass
    e_charge: 1.60217657e-19    // C                - Electron's charge
    E_field: 1000000            // V/m              - External field
    EV: 1.602e-19               // J                - Joules in one electronvolt
