#
# This is a simple sample config
#
# Note: particles count quantity synonim is 'particles_count'
model:
    name: One dimension test config
    cordinate_space_grid:
        x_coord:
            name: Horisontal coordinate, m
            division:
                mode: uniform
                min: -10.0
                max: 10.0
                segments_count: 100
    fractions:
        fraction1:
            name: Test Fraction One
            fraction_space_grid:
                x_speed:
                    name: Horisontal speed, m/s
                    division:
                        mode: uniform
                        min: -10.0
                        max: 10.0
                        segments_count: 50
            quantities:
                testQuantity1:
                    name: Test quantity 1
            sources: |
                // Generating initial state of particles
                    if (model->time < 0.02)
                        if (fabs(x_speed+3) < 0.5 || fabs(x_speed-3) < 0.5)
                            if (fabs(x_coord) < 1) {
                                particles_count.NEXT = 1;
                                testQuantity1.NEXT = 1;
                            }
            space_coords_derivatives: |
                x_coord.DER = x_speed;
            fraction_coords_derivatives: |
                x_speed.DER = 0; // -9.8;
output:
    concentration_vs_x:
        name: Concentration vs X coordinate
        mode: quantity_vs_space_coord
        space_point:
            x_coord: 0
        iterating_coord: x_coord
        fraction: fraction1
        output_code: |
            cell.quantities[FRACTION1_QUANTITIES_PARTICLES_COUNT] / cell.volume
        file_name: "Fraction1-concentration-x-slice-(t).txt"
        points_count: 100
        time_step: 0.01
    
    test_quantity_1_vs_x:
        name: Test quantity 1 vs coordinate
        mode: quantity_vs_space_coord
        space_point:
            x_coord: 0
        iterating_coord: x_coord
        fraction: fraction1
        output_code: |
            cell.quantities[FRACTION1_QUANTITIES_TESTQUANTITY1] / cell.volume
        file_name: "Fraction1-test-quantity-x-slice-(t).txt"
        points_count: 100
        time_step: 0.01

run_options:
    start_time: 0
    stop_time: 5
    time_step: 0.01
