#
# This is a simple sample config
#
# Note: particles count quantity synonim is 'particles_count'
model:
    name: One dimension test config
    cordinate_space_grid:
        x_coord:
            name: Horisontal coordinate, m
            division:
                mode: uniform
                min: -10.0
                max: 10.0
                segments_count: 100
    fractions:
        fraction1:
            name: Test Fraction One
            fraction_space_grid:
                x_speed:
                    name: Horisontal speed, m/s
                    division:
                        mode: uniform
                        min: -10.0
                        max: 10.0
                        segments_count: 50
            quantities:
                testQuantity1:
                    name: Test quantity 1
            sources: |
                // Generating initial state of particles
                    if (model->time < 0.02)
                        if (fabs(x_speed+3) < 0.5 || fabs(x_speed-3) < 0.5)
                            if (fabs(x_coord) < 1) {
                                particles_count.NEXT = 1;
                                testQuantity1.NEXT = 1;
                            }
            space_coords_derivatives: |
                x_coord.DER = x_speed;
            fraction_coords_derivatives: |
                x_speed.DER = -2;
            
            boundary_conditions:
                # Default value is wall
                x_coord:
                    top: open
                    bottom: open
output:
    concentration_vs_x:
        name: Concentration-graph
        fraction: fraction1
        quantity: particles_count
        space_point:
            x_coord: 0
        fraction_point:
            x_speed: 0
        output_axis:
            x_coord:
                points_count: 100
        convolution:
          - x_speed
        #convolution: all
        time_step: 0.01
    n_vs_x_and_v:
        name: Concentration-vs-x-and-v
        fraction: fraction1
        quantity: particles_count
        space_point:
            x_coord: 0
        fraction_point:
            x_speed: 0
        output_axis:
            x_coord:
                points_count: 100
            x_speed:
                points_count: 100
        time_step: 0.2

run_options:
    start_time: 0
    stop_time: 5
    time_step: 0.01
