#
# This is a simple sample config
#
# Note: particles count quantity synonim is 'particles_count'
model:
    name: One dimension test config
    cordinate_space_grid:
        x_coord:
            name: Vertical coordinate, m
            division:
                mode: uniform
                min: -30.0
                max: 15.0
                segments_count: 100
    fractions:
        fraction1:
            name: Abstract fraction
            fraction_space_grid:
                x_speed:
                    name: Vertical speed, m/s
                    division:
                        mode: uniform
                        min: -40.0
                        max: 30.0
                        segments_count: 50
            quantities:
                testQuantity1:
                    name: Test quantity 1
            init_quantities: |
                if (fabs(x_speed+10) < 2 || fabs(x_speed-10) < 2)
                    if (fabs(x_coord) < 4) {
                        particles_count = 1;
                        //testQuantity1 = 1;
                    }
            sources: |
                    
            space_coords_derivatives: |
                x_coord.DER = x_speed;
            fraction_coords_derivatives: |
                x_speed.DER = gx;
            
            boundary_conditions:
                # Default value is wall
                x_coord:
                    top: open
                    bottom: open
output:
    concentration_vs_x:
        name: Concentration-graph
        fraction: fraction1
        quantity: particles_count
        space_point:
            x_coord: 0
        fraction_point:
            x_speed: 0
        output_axis:
            x_coord:
                points_count: 100
        convolution:
          - x_speed
        #convolution: all
        time_step: 0.1
    n_vs_x_and_v:
        name: Concentration-vs-x-and-v
        fraction: fraction1
        quantity: particles_count
        space_point:
            x_coord: 0
        fraction_point:
            x_speed: 0
        output_axis:
            x_coord:
                points_count: 100
            x_speed:
                points_count: 100
        time_step: 0.2

run_options:
    start_time: 0
    stop_time: 5
    time_step: 0.01
    threads_count: 3

constants:
    gx: -9.8
