model:
    name: One dimension test config
    cordinate_space_grid:
        x_coord:
            name: Horisontal coordinate, m
            division:
                mode: uniform
                min: -10.0
                max: 10.0
                segments_count: 100
    fractions:
        fraction1:
            name: Test Fraction One
            fraction_space_grid:
                x_speed:
                    name: Horisontal speed, m/s
                    division:
                        mode: uniform
                        min: -10.0
                        max: 10.0
                        segments_count: 50
            quantities:
                testQuantity1:
                    name: Test quantity 1
            sources: |
                SpaceGridType::GridElementBase* spaceCell = getSpaceCell();
                    // Generating initial state of particles
                    if (static_cast<Model*>(getModel())->time < 0.02)
                    if (fabs(coordinates[FRACTION1_COORDS_X_SPEED]+3) < 0.5)
                    if (fabs(spaceCell->coordinates[SPACE_COORDS_X_COORD]-8) < 1)
                    //    nextStepQuantities[FRACTION1_QUANTITY_COUNT] += 0.1*spaceCell->volume*dt;
                    nextStepQuantities[FRACTION1_QUANTITIES_PARTICLES_COUNT] = 1;//spaceCell->coordinates[SPACE_COORDS_X]/30;
            space_coords_derivatives: |
                spaceCoordsDerivatives[SPACE_COORDS_X_COORD] = this->coordinates[FRACTION1_COORDS_X_SPEED];
            fraction_coords_derivatives: |
                fractionCoordsDerivatives[FRACTION1_COORDS_X_SPEED] = 0;// -9.8;
output:
    concentration_vs_x:
        name: Concentration vs X coordinate
