model:
    name: One dimension test config
    cordinate_space_grid:
      - id: x_coord
        name: Horisontal coordinate, m
        division:
            mode: uniform
            min: -10
            max: 10
            segments_count: 100
    fractions:
      - id: fraction1
        name: Test Fraction One
        fraction_space_grid:
          - id: x_speed
            name: Horisontal speed, m/s
            division:
                mode: uniform
                min: -10
                max: 10
                segments_count: 100
        quantities:
          - id: testQuantity1
            name: Test quantity 1
        sources:
        space_coords_derivatives: |
            spaceCoordsDerivatives[SPACE_COORDS_X] = this->coordinates[FRACTION1_COORDS_VX];
        fraction_coords_derivatives: |
            fractionCoordsDerivatives[FRACTION1_COORDS_VX] = 0; // -9.8;
