#
# This is a simple sample config
#
# Note: particles count quantity synonim is 'particles_count'
model:
    name: One dimension test config
    cordinate_space_grid:
        x_coord:
            name: Coordinate X, m
            division:
                mode: uniform
                min: -15.0
                max: 15.0
                segments_count: 100
        y_coord:
            name: Coordinate Y, m
            division:
                # mode: specific
                # filename: test.txt
                mode: uniform
                min: -10.0
                max: 10.0
                segments_count: 100
    fractions:
        fraction1:
            name: Test Fraction One
            fraction_space_grid:
            quantities:
                quantity_that_diffuse:
                    name: Quantity with diffusion turned on
            init_quantities: |
                // Particles! Particles everywhere!
                particles_count.NEXT = 1 * space_volume;
                
                if (fabs(x_coord) < 2 && fabs(y_coord) < 2)
                    quantity_that_diffuse.NEXT = 1 * space_volume;
            sources: |
                // Always constant heat in square 2x2 with center (0, 0)
                if (fabs(x_coord) < 2 && fabs(y_coord) < 2)
                    quantity_that_diffuse.NEXT = 1 * space_volume;
                
            space_coords_derivatives: |
                // The wind here
                x_coord.DER = 0.5;
                //y_coord.DER = 0.0;
            fraction_coords_derivatives: |
            boundary_conditions:
                # Default value is wall
                x_coord:
                    top: open
                    bottom: open
                y_coord:
                    top: wall
                    bottom: wall
            diffusion:
                quantity_that_diffuse:
                    x_coord: |
                        diffusion = 1.0;
                    y_coord: |
                        diffusion = 1.0;
output:
    concentration_vs_coords:
        name: Concentration-vs-coords
        fraction: fraction1
        quantity: particles_count
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            x_coord:
                points_count: 100
            y_coord:
                points_count: 100
        time_step: 0.2
    
    diff_q_vs_coords:
        name: Quantity-that-diffuse-vs-coords
        fraction: fraction1
        quantity: quantity_that_diffuse
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            x_coord:
                points_count: 100
            y_coord:
                points_count: 100
        time_step: 0.2

run_options:
    start_time: 0
    stop_time: 10
    time_step: 0.01
