#
# This is a simple sample config
#
# Note: particles count quantity synonim is 'particles_count'
model:
    name: Dry air in square 2d box
    cordinate_space_grid:
        x_coord:
            name: Coordinate X, m
            division:
                mode: uniform
                min: -25.0
                max: 25.0
                segments_count: 100
        y_coord:
            name: Coordinate Y, m
            division:
                # mode: specific
                # filename: test.txt
                mode: uniform
                min: -25.0
                max: 25.0
                segments_count: 100
    fractions:
        air:
            name: Air
            fraction_space_grid:
            quantities:
                particles_count:
                    name: Count of air, moll
                internal_energy:
                    name: The internal energy of air, J
            secondary_quantities:
                pressure:
                    name: Air pressure, N/m^2
                    counting: |
                        pressure = (1.4-1) * internal_energy / space_volume;
            sources: |
                // Generating initial state of particles
                if (model->time < 0.02) {
                    // Particles! Particles everywhere!
                    particles_count.NEXT = 1000 /*L*/ / 22.4 /*L/Moll*/ * space_volume;
                    internal_energy.NEXT = 1/(1.4-1) * particles_count.NEXT * 8.31*300;
                    // pressure
                }
            space_coords_derivatives: |
                //x_coord.DER = 0.5;
                //y_coord.DER = 0.0;
            fraction_coords_derivatives: |
            boundary_conditions:
                # Default value is wall
                x_coord:
                    top: wall
                    bottom: wall
                y_coord:
                    top: wall
                    bottom: wall
            diffusion:
                internal_energy:
                    x_coord: |
                        diffusion = 1.0;
                    y_coord: |
                        diffusion = 1.0;
output:
    air_count_vs_coords:
        name: Air-count-vs-coords
        fraction: air
        quantity: particles_count
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            x_coord:
                points_count: 100
            y_coord:
                points_count: 100
        time_step: 0.2
    
    air_energy_vs_coords:
        name: Air-energy-vs-coords
        fraction: air
        quantity: internal_energy
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            x_coord:
                points_count: 100
            y_coord:
                points_count: 100
        time_step: 0.2
        
    air_pressure_vs_coords:
        name: Air-pressure-vs-coords
        fraction: air
        quantity: pressure
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            x_coord:
                points_count: 100
            y_coord:
                points_count: 100
        time_step: 0.2
    
run_options:
    start_time: 0
    stop_time: 10
    time_step: 0.01
