#
# This is a simple sample config
#
# Note: particles count quantity synonim is 'particles_count'
model:
    name: Dry air in square 2d box
    cordinate_space_grid:
        x_coord:
            name: Coordinate X, m
            division:
                mode: uniform
                min: -25.0
                max: 25.0
                segments_count: 1
        y_coord:
            name: Coordinate Y, m
            division:
                # mode: specific
                # filename: test.txt
                mode: uniform
                min: -25.0
                max: 25.0
                segments_count: 50
    fractions:
        air:
            name: Air
            stabilisation: on
            #fraction_space_grid:
            extensive_quantities:
                particles_count:
                    name: Count of air, moll
                internal_energy:
                    name: The internal energy of air, J
                x_impulse:
                    name: Horisontal impulse, g*m/c
                y_impulse:
                    name: Vertical impulse, g*m/c
            
            intensive_quantities:
                pressure:
                    name: Air pressure, N/m^2
                    counting: |
                        pressure = (1.4-1) * internal_energy / space_volume;
                temperature:
                    name: Air temperature, K
                    counting: |
                        temperature = (1.4-1) * internal_energy / (8.31 * particles_count);
                thermal_conduction_coefficient:
                    name: Thermal conduction coefficient, 
                    counting: |
                        thermal_conduction_coefficient = 0;//100000;//0.026;
                diffusion_coefficient:
                    name: Air steady-state diffusion coefficient, m^2/s
                    counting: |
                        diffusion_coefficient = 1.0/3.0*sqrt(8.0*8.31*temperature/M_PI/0.029)  *  1/(sqrt(2.0) * M_PI * (3e-10)*(3e-10) * particles_count * 6e23);
                velocity_x:
                    name: Particles velocity in X direction, m/s
                    counting: |
                        velocity_x = x_impulse / (particles_count * 0.029 /*kg/Moll*/);
                velocity_y:
                    name: Particles velocity in Y direction, m/s
                    counting: |
                        velocity_y = y_impulse / (particles_count * 0.029 /*kg/Moll*/);
                        
            init_quantities: |
                particles_count = 1000.0 /*L*/ / 22.4 /*L/Moll*/ * space_volume;
                internal_energy = 1/(1.4-1) * particles_count * 8.31*300;
                x_impulse = 0.0;
                y_impulse = 0.0; 
                
            sources: |
                AirCell* next = static_cast<AirCell*>(nextInSpace(SPACE_COORDS_Y_COORD));
                AirCell* prev = static_cast<AirCell*>(prevInSpace(SPACE_COORDS_Y_COORD));
                if (!next)
                    next = this;
                if (!prev)
                    prev = this;
                
                double sizeX = getSpaceCell()->size[SPACE_COORDS_X_COORD];
                double sizeY = getSpaceCell()->size[SPACE_COORDS_Y_COORD];
                double nextSizeY = next->getSpaceCell()->size[SPACE_COORDS_Y_COORD];
                
                double prevSurfPressure = interpolateIntensiveQunatityOnSpaceCellsContact(AIR_INTENSIVE_QUANTITIES_PRESSURE, prev, SPACE_COORDS_Y_COORD);
                double nextSurfPressure = interpolateIntensiveQunatityOnSpaceCellsContact(AIR_INTENSIVE_QUANTITIES_PRESSURE, next, SPACE_COORDS_Y_COORD);
                
                AirCell* pressureNext = next;
                AirCell* pressurePrev = prev;
                /*
                if (y_impulse < 0)
                    pressurePrev = this;
                else
                    pressureNext = this;
                */
                y_impulse.DELTA += (-9.8 * particles_count * 0.029 /*kg/Moll*/ 
                    + (pressurePrev->pressure - pressureNext->pressure) * sizeX
                    //+ (prevSurfPressure - nextSurfPressure) * sizeX
                    ) * dt;
                
                /*
                if (next == this || prev == this)
                    y_impulse.DELTA = 0;
                */
                
                if (isNotNull(particles_count)) {
                    // internal_energy.DELTA += 8e-3 * volume * pressure / particles_count * particles_count.DELTA;
                    double prevSurfVelocity = 0;
                    double nextSurfVelocity = 0;
                    if (prev != this)
                        prevSurfVelocity = interpolateIntensiveQunatityOnSpaceCellsContact(AIR_INTENSIVE_QUANTITIES_VELOCITY_Y, prev, SPACE_COORDS_Y_COORD);
                    if (next != this)
                        nextSurfVelocity = interpolateIntensiveQunatityOnSpaceCellsContact(AIR_INTENSIVE_QUANTITIES_VELOCITY_Y, next, SPACE_COORDS_Y_COORD);
                    internal_energy.DELTA -= pressure * (nextSurfVelocity - prevSurfVelocity) * sizeX * dt;
                }
                
                double heatTransfer = thermal_conduction_coefficient * (temperature - next->temperature) / ((sizeY + nextSizeY) / 2) * sizeX * dt;
                internal_energy.DELTA -= heatTransfer;
                next->internal_energy.DELTA += heatTransfer;
                
            space_coords_derivatives: |
                x_coord.DER = velocity_x;
                y_coord.DER = velocity_y;
            
            #fraction_coords_derivatives: |
            boundary_conditions:
                # Default value is 'wall', also allowed 'open'
                x_coord:
                    top: wall
                    bottom: wall
                    #top: open
                    #bottom: open
                y_coord:
                    top: wall
                    bottom: wall
                    #top: open
                    #bottom: open
            diffusion:
                x_coord: |
                    diffusion = 0.0;
                y_coord: |
                    diffusion = 0.0;
output:
    air_count_vs_coords:
        name: Air-count-vs-coords
        fraction: air
        quantity: particles_count
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            #x_coord:
            #    points_count: 4
            y_coord:
                points_count: 100
        time_step: 0.01
    
    air_energy_vs_coords:
        name: Air-energy-vs-coords
        fraction: air
        quantity: internal_energy
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            #x_coord:
            #    points_count: 4
            y_coord:
                points_count: 100
        time_step: 0.01
        
    air_pressure_vs_coords:
        name: Air-pressure-vs-coords
        fraction: air
        quantity: pressure
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            #x_coord:
            #    points_count: 4
            y_coord:
                points_count: 100
        time_step: 0.01
    
    air_temperature_vs_coords:
        name: Air-temperature-vs-coords
        fraction: air
        quantity: temperature
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            #x_coord:
            #    points_count: 4
            y_coord:
                points_count: 100
        time_step: 0.01
    
    diffusion_coefficient:
        name: Air-diffusion-coefficient-vs-coords
        fraction: air
        quantity: diffusion_coefficient
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            #x_coord:
            #    points_count: 4
            y_coord:
                points_count: 100
        time_step: 0.01
    
    vertical_impulse_vs_coords:
        name: Air-vertical-impulse-vs-coords
        fraction: air
        quantity: y_impulse
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            #x_coord:
            #    points_count: 4
            y_coord:
                points_count: 100
        time_step: 0.01
run_options:
    start_time: 0
    stop_time: 1
    time_step: 0.00001
    stabilisation_period: 0.00300
    threads_count: 3
