#
# This is a simple sample config
#
# Note: particles count quantity synonim is 'particles_count'
model:
    name: Dry air in square 2d box
    cordinate_space_grid:
        x_coord:
            name: Coordinate X, m
            division:
                mode: uniform
                min: -25.0
                max: 25.0
                segments_count: 2
        y_coord:
            name: Coordinate Y, m
            division:
                # mode: specific
                # filename: test.txt
                mode: uniform
                min: -25.0
                max: 25.0
                segments_count: 100
    fractions:
        air:
            name: Air
            #fraction_space_grid:
            extensive_quantities:
                particles_count:
                    name: Count of air, moll
                internal_energy:
                    name: The internal energy of air, J
                x_impulse:
                    name: Horisontal impulse, g*m/c
                y_impulse:
                    name: Vertical impulse, g*m/c
            
            intensive_quantities:
                pressure:
                    name: Air pressure, N/m^2
                    counting: |
                        pressure = (1.4-1) * internal_energy / space_volume;
                temperature:
                    name: Air temperature, K
                    counting: |
                        temperature = (1.4-1) * internal_energy / (8.31 * particles_count);
                thermal_conduction_coefficient:
                    name: Thermal conduction coefficient, 
                    counting: |
                        thermal_conduction_coefficient = 0;
            
            init_quantities: |
                particles_count = 1000 /*L*/ / 22.4 /*L/Moll*/ * space_volume;
                internal_energy = 1/(1.4-1) * particles_count * 8.31*300;
                x_impulse = 0.0;
                y_impulse = 0; // -8 * particles_count * 29 /*g/Moll*/;
                
            sources: |
                AirCell* next = static_cast<AirCell*>(nextInSpace(SPACE_COORDS_Y_COORD));
                AirCell* prev = static_cast<AirCell*>(prevInSpace(SPACE_COORDS_Y_COORD));
                if (!next)
                    next = this;
                if (!prev)
                    prev = this;
                
                y_impulse.DELTA += (-9.8 * particles_count * 29 /*g/Moll*/ 
                    + (prev->pressure - next->pressure) * getSpaceCell()->size[SPACE_COORDS_X_COORD]
                    ) * dt;
                
            space_coords_derivatives: |
                if (isNotNull(particles_count)) {
                    x_coord.DER = x_impulse / (particles_count * 29 /*g/Moll*/);
                    y_coord.DER = y_impulse / (particles_count * 29 /*g/Moll*/);
                } else {
                    x_coord.DER = 0.0;
                    y_coord.DER = 0.0;
                }
            
            #fraction_coords_derivatives: |
            boundary_conditions:
                # Default value is 'wall', also allowed 'open'
                x_coord:
                    top: wall
                    bottom: wall
                    #top: open
                    #bottom: open
                y_coord:
                    top: wall
                    bottom: wall
                    #top: open
                    #bottom: open
            diffusion:
                particles_count:
                    x_coord: |
                        diffusion = 0.0;
                    y_coord: |
                        diffusion = 10.0;
                internal_energy:
                    x_coord: |
                        diffusion = 0.0;
                    y_coord: |
                        diffusion = 0.0;
output:
    air_count_vs_coords:
        name: Air-count-vs-coords
        fraction: air
        quantity: particles_count
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            #x_coord:
            #    points_count: 4
            y_coord:
                points_count: 100
        time_step: 0.5
    
    air_energy_vs_coords:
        name: Air-energy-vs-coords
        fraction: air
        quantity: internal_energy
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            #x_coord:
            #    points_count: 4
            y_coord:
                points_count: 100
        time_step: 0.5
        
    air_pressure_vs_coords:
        name: Air-pressure-vs-coords
        fraction: air
        quantity: pressure
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            #x_coord:
            #    points_count: 4
            y_coord:
                points_count: 100
        time_step: 0.5
    
    air_temperature_vs_coords:
        name: Air-temperature-vs-coords
        fraction: air
        quantity: temperature
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            #x_coord:
            #    points_count: 4
            y_coord:
                points_count: 100
        time_step: 0.5
    
    vertical_impulse_vs_coords:
        name: Air-vertical-impulse-vs-coords
        fraction: air
        quantity: y_impulse
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            #x_coord:
            #    points_count: 4
            y_coord:
                points_count: 100
        time_step: 0.5
run_options:
    start_time: 0
    stop_time: 40
    time_step: 0.001
    threads_count: 3
