#
# This is a simple sample config
#
# Note: particles count quantity synonim is 'particles_count'
model:
    name: Dry air in square 2d box
    cordinate_space_grid:
        x_coord:
            name: Coordinate X, m
            division:
                mode: uniform
                min: -25.0
                max: 25.0
                segments_count: 50
        y_coord:
            name: Coordinate Y, m
            division:
                # mode: specific
                # filename: test.txt
                mode: uniform
                min: -25.0
                max: 25.0
                segments_count: 50
    fractions:
        air:
            name: Air
            stabilisation: on
            #fraction_space_grid:
            extensive_quantities:
                particles_count:
                    name: Count of air, moll
                internal_energy:
                    name: The internal energy of air, J
                x_impulse:
                    name: Horisontal impulse, g*m/c
                y_impulse:
                    name: Vertical impulse, g*m/c
            
            intensive_quantities:
                pressure:
                    name: Air pressure, N/m^2
                    counting: |
                        pressure = (1.4-1) * internal_energy / space_volume;
                temperature:
                    name: Air temperature, K
                    counting: |
                        temperature = (1.4-1) * internal_energy / (R * particles_count);
                thermal_conduction_coefficient:
                    name: Thermal conduction coefficient, 
                    counting: |
                        thermal_conduction_coefficient = 0;//100000;//0.026;
                diffusion_coefficient:
                    name: Air steady-state diffusion coefficient, m^2/s
                    counting: |
                        diffusion_coefficient = 1.0/3.0*sqrt(8.0*R*temperature/M_PI/Mair) * 1/(sqrt(2.0) * M_PI * (3e-10)*(3e-10) * particles_count * Na);
                velocity_x:
                    name: Particles velocity in X direction, m/s
                    counting: |
                        velocity_x = x_impulse / (particles_count * Mair );
                velocity_y:
                    name: Particles velocity in Y direction, m/s
                    counting: |
                        velocity_y = y_impulse / (particles_count * Mair );
                        
            init_quantities: |
                particles_count = 1000.0 /*L*/ / 22.4 /*L/Moll*/ * space_volume;
                internal_energy = 1/(1.4-1) * particles_count * R *300;
                x_impulse = 0.0;
                y_impulse = 0.0; 
                
            sources: |
                AirCell* nextY = static_cast<AirCell*>(nextInSpace(SPACE_COORDS_Y_COORD));
                AirCell* prevY = static_cast<AirCell*>(prevInSpace(SPACE_COORDS_Y_COORD));
                if (!nextY)
                    nextY = this;
                if (!prevY)
                    prevY = this;
                
                AirCell* nextX = static_cast<AirCell*>(nextInSpace(SPACE_COORDS_X_COORD));
                AirCell* prevX = static_cast<AirCell*>(prevInSpace(SPACE_COORDS_X_COORD));
                
                if (!nextX)
                    nextX = this;
                if (!prevX)
                    prevX = this;
                
                double sizeX = getSpaceCell()->size[SPACE_COORDS_X_COORD];
                double sizeY = getSpaceCell()->size[SPACE_COORDS_Y_COORD];
                
                double nextYSizeY = nextY->getSpaceCell()->size[SPACE_COORDS_Y_COORD];
                double nextXSizeX = nextX->getSpaceCell()->size[SPACE_COORDS_X_COORD];
                
                x_impulse.DELTA += (//gy * particles_count * Mair 
                    + (prevX->pressure - nextX->pressure) * sizeY
                    ) * dt;
                
                y_impulse.DELTA += (//gy * particles_count * Mair 
                    + (prevY->pressure - nextY->pressure) * sizeX
                    ) * dt;
                
                
                if (isNotNull(particles_count)) {
                    // internal_energy.DELTA += 8e-3 * volume * pressure / particles_count * particles_count.DELTA;
                    double prevSurfVelocity = 0;
                    double nextSurfVelocity = 0;
                    if (prevY != this)
                        prevSurfVelocity = interpolateIntensiveQunatityOnSpaceCellsContact(AIR_INTENSIVE_QUANTITIES_VELOCITY_Y, prevY, SPACE_COORDS_Y_COORD);
                    if (nextY != this)
                        nextSurfVelocity = interpolateIntensiveQunatityOnSpaceCellsContact(AIR_INTENSIVE_QUANTITIES_VELOCITY_Y, nextY, SPACE_COORDS_Y_COORD);
                    internal_energy.DELTA -= pressure * (nextSurfVelocity - prevSurfVelocity) * sizeX * dt;
                }
                
                double heatTransferY = thermal_conduction_coefficient * (temperature - nextY->temperature) / ((sizeY + nextYSizeY) / 2) * sizeX * dt;
                double heatTransferX = thermal_conduction_coefficient * (temperature - nextX->temperature) / ((sizeX + nextXSizeX) / 2) * sizeY * dt;
                
                internal_energy.DELTA -= heatTransferY + heatTransferX;
                nextY->internal_energy.DELTA += heatTransferY;
                nextX->internal_energy.DELTA += heatTransferX;
                
                
                // Heating source at center
                if (fabs(x_coord) < 1 && fabs(y_coord) < 1 /* && prevY == this*/ && temperature < 400) {
                    // Heating up to 400 during time ~ 10s
                    internal_energy += 1/(1.4-1) * particles_count * R * (400-temperature)/10 * dt;
                }
                
            space_coords_derivatives: |
                x_coord.DER = velocity_x;
                y_coord.DER = velocity_y;
            
            #fraction_coords_derivatives: |
            boundary_conditions:
                # Default value is 'wall', also allowed 'open'
                x_coord:
                    top: wall
                    bottom: wall
                    #top: open
                    #bottom: open
                y_coord:
                    top: wall
                    bottom: wall
                    #top: open
                    #bottom: open
            diffusion:
                x_coord: |
                    diffusion = 0;//diffusion_coefficient;
                y_coord: |
                    diffusion = 0;//diffusion_coefficient;
output:
    air_count_y_slice:
        name: Air-count-y-slice
        fraction: air
        quantity: particles_count
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            #x_coord:
            #    points_count: 4
            y_coord:
                points_count: 100
        time_step: 0.01
    
    air_count_distribution:
        name: Air-count
        fraction: air
        quantity: particles_count
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            x_coord:
                points_count: 50
            y_coord:
                points_count: 50
        time_step: 0.1
    
    air_temperature_distribution:
        name: Air-temperature
        fraction: air
        quantity: temperature
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            x_coord:
                points_count: 50
            y_coord:
                points_count: 50
        time_step: 0.1
    
    air_vx_distribution:
        name: Air-vx
        fraction: air
        quantity: velocity_x
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            x_coord:
                points_count: 50
            y_coord:
                points_count: 50
        time_step: 0.1
    
    air_vy_distribution:
        name: Air-vy
        fraction: air
        quantity: velocity_y
        space_point:
            x_coord: 0
            y_coord: 0
        output_axis:
            x_coord:
                points_count: 50
            y_coord:
                points_count: 50
        time_step: 0.1
    
run_options:
    start_time: 0
    stop_time: 1
    time_step:            0.00001
    stabilisation_period: 0.00150
    threads_count: 3

constants:
    Mair: 0.029 // kg / Moll 
    Na: 6.02e23 // particles / Moll
    R: 8.3144 // J / Moll*K
    #gy: -9.8 // m / s^2
    gy: -4.8 // m / s^2
