model:
    name: Test model not related to thundercloud
    cordinate_space_grid:
        - id: x_coord
          name: Horisontal coordinate, m
          division:
              mode: specific
              segments_file: configs/x_segments.txt
        - id: y_coord
          name: Vertical coordinate, m
          division:
              mode: uniform
              min: 0
              max: 10
              segments_count: 10
    
    fractions:
        - id: fract1
          name: Test Fraction One
          fraction_space_grid:
              - id: y_speed
                name: Vertical speed, m/s
                division:
                    mode: uniform
                    min: -100
                    max: 100
                    segments_count: 20
              - id: x_speed
                name: Horisontal speed, m/s
                division:
                    mode: uniform
                    min: -10
                    max: 10
                    segments_count: 10
          quantities:
              - id: concentration
                name: Concentration of particles
